name: prometheus-node-exporter
home: https://github.com/prometheus/node_exporter/
sources:
    - https://github.com/prometheus/node_exporter/
version: 4.32.0
description: A Helm chart for prometheus node-exporter
keywords:
    - node-exporter
    - prometheus
    - exporter
maintainers:
    - name: gianrubio
      email: gianrubio@gmail.com
      url: ""
    - name: zanhsieh
      email: zanhsieh@gmail.com
      url: ""
    - name: zeritti
      email: rootsandtrees@posteo.de
      url: ""
icon: ""
apiversion: v2
condition: ""
tags: ""
appversion: 1.7.0
deprecated: false
annotations:
    artifacthub.io/license: Apache-2.0
    artifacthub.io/links: |
        - name: Chart Source
          url: https://github.com/prometheus-community/helm-charts
kubeversion: ""
dependencies: []
type: application
